@startuml "Azioni dei PG"
skinparam defaultFontName Oxanium
skinparam activity {
  StartColor #0fff50
  BarColor #2c84fa
  EndColor #e949f5
  BorderColor #2c84fa
  ArrowColor #2c84fa
  FontName Oxanium
}
title "Azioni dei PG" 
start
:Il giocatore specifica cosa vuole fare;
if (C'è un rischio
di un fallimento?) then (<color:#f2f230>  sì)
:Richiedi il tiro salvezza;
  note right
   Attivazione 
   cybermodifica
  endnote
  if (le circostanze esterne 
aumentano o riducono 
il rischio?) then (<color:#f2f230> no)
    :tira un 1d20;
  else (<color:#f2f230> sì)
   switch (tipo di circostanze) 
   case ( <color:#f2f230> rischio minore)
   :tira 2d20, seleziona il punteggio **più basso**;
   case ( <color:#f2f230> rischio maggiore)
   :tira 2d20, seleziona il punteggio **più alto**;
   endswitch
  endif 
  if (Risultato inferiore o uguale 
  all'attuale livello di abilità?) then (<color:#f2f230> sì)
  #0fff50 :**SUCCESSO**;
  else (<color:#f2f230> no)
  #ff54ff :**FALLIMENTO**;
  endif
else (<color:#f2f230> no)
#0fff50 :**SUCCESSO**;
endif 
end
@enduml

@startuml "Combattimento fisico"
title "Combattimento fisico"
skinparam defaultFontName Oxanium
skinparam activity {
  StartColor #0fff50
  BarColor #2c84fa
  EndColor #e949f5
  BorderColor #2c84fa
  ArrowColor #2c84fa
  FontName Oxanium
}
start
:Inizia del round;
if (Il giocatore vuole 
ritirarsi dal combattimento?) then (<color:#f2f230> sì)
:Chiedi una prova di BIO;
 note left
   Attivazione 
   cybermodifica
 endnote
if (Prova superata e il giocatore
ha un posto sicuro dove rifugiarsi?) then (<color:#f2f230> sì)
:Il giocatore abbandona il combattimento;
stop
else (<color:#f2f230> no)
:Il giocatore continua a combattere;
endif
endif
if (il personaggio può essere colto di sorpresa
    e vuole agire prima degli avversari?) then (<color:#f2f230> sì)
  :Chiedi una prova di BIO;
  note left
   Attivazione 
   cybermodifica
  endnote
  if (Prova di BIO passata?) then (<color:#f2f230> sì)
    :Il personaggio agisce prima degli avversari;
  else (<color:#f2f230> no)
    :Tutte le azioni del round
     avvengono simultaneamente;
  endif
else (<color:#f2f230> no)
    :Tutte le azioni del round
     avvengono simultaneamente;
endif
:Il personaggio può muoversi;
:Un personaggio può eseguire un attacco o un'altra azione;
if (Attacco o azione?) then (<color:#f2f230> attacco)
#f2f230 :Salta l'algoritmo di attacco;
else (<color:#f2f230> azione)
  if (l'azione è rischiosa?) then (<color:#f2f230> sì)
    :Richiedi un tiro di salvezza adeguato;
    note left
   Attivazione 
   cybermodifica
    endnote
    if (Prova superata?) then (<color:#f2f230> sì)
    #0fff50 :**SUCCESSO**;
    else (<color:#f2f230> no)
    #ff54ff:**FALLIMENTO**;
    endif
  else (<color:#f2f230> no)
    #0fff50 :**SUCCESSO**;
  endif 
endif
end
@enduml

@startuml "Attacco fisico"
title "Attacco fisico"
skinparam defaultFontName Oxanium
skinparam activity {
  StartColor #0fff50
  BarColor #2c84fa
  EndColor #e949f5
  BorderColor #2c84fa
  ArrowColor #2c84fa
  FontName Oxanium
}
start
group Determina \nla taglia del\ndado di danno
:un dado danno standard;
if (many attackers?) then (<color:#f2f230> sì)
:aggiungi un dado per ogni attaccante;
else (<color:#f2f230> no)
endif
if (attacco a doppia arma?) then (<color:#f2f230> sì)
:aggiungere un dado per ciascun \nattaccante con una doppia arma;
else (<color:#f2f230> no)
endif
end group
group Determinare \nil tipo di\ndadi danno
:Individualmente per ogni attaccante;
if (attaccare senza un'arma definita?) then (<color:#f2f230> sì)
:1d4;
else (<color:#f2f230> no)
:dadi danno dell'arma;
switch (modificatore di attacco)
case (<color:#f2f230> posizione compromessa)
:1d4o rispettivamente
dado dell'arma __compromesso__ ;
case (<color:#f2f230> vantaggio)
:1d12 o rispettivamente
dado dell'arma __potenziato__;
endswitch 
endif
end group
:Fai un tiro di dadi;
note right
Attivazione cybermodifiche dell'attaccante
end note
if (L'arma ha la caratterisca "scoppio"?) then (<color:#f2f230> sì)
:ripetere il tiro per i danni
per ogni personaggio
nel raggio d'azione;
endif
:Seleziona il punteggio più alto;
:Sottrai il valore di armatura 
__effettivo__ della vittima 
dal risultato del tiro;
if (PF dell'avversario inferiori o uguali a zero?) then (<color:#f2f230> no)
:Sottrai i punti danno
dagli __effettivi__ PF dell'avversario;
note right
Attivazione Cybermodifiche
dell'avversario
endnote
else (<color:#f2f230> sì)
endif 
if (numero di punti danno rimanenti maggiore di zero?) then (<color:#f2f230> sì)
:sottrarre la quantità rimanente di punti danno
dalla BIO del tuo avversario;
note right
Attivazione Cybermodifiche
dell'avversario
endnote
:Esegui una prova di danno critico;
if (Prova superata?) then (<color:#f2f230> sì)
  end
else (<color:#f2f230> no)
  :applica tutti gli effetti
  di danno critico;
  note right
  Attivazione
  cybermodifiche
  endnote
endif
else (<color:#f2f230> no)
 end
endif
end
@enduml

@startuml "Attacco nell'Infosfera"
title "Attacco nell'Infosfera"
skinparam defaultFontName Oxanium
skinparam activity {
  StartColor #0fff50
  BarColor #2c84fa
  EndColor #e949f5
  BorderColor #2c84fa
  ArrowColor #2c84fa
  FontName Oxanium
}
start
group Determina \ni dadi danno
:Dadi danno del neuroprocessore come standard;
if (attaccanti multipli?) then (<color:#f2f230> sì)
:aggiungi un dado per ogni attaccante;
else (<color:#f2f230> no)
endif
end group
:Fai un tiro;
:Seleziona un attaccante e
ricorda il risultato del suo tiro
(attacco al neuroprocessore);
:aggiungi i dadi
di attivazione software;
note right
Attivazione del software
dell'attaccante selezionato
endnote 
:eseguire un tiro aggiuntivo
di dadi danno software
e aggiungi il risultato
all'attacco al neuroprocessore;
:Sottrai il valore
di armatura INF dell'avversario
dal risultato;
note right
Attivazione
software nodo
endnote
if (PF del nodo minori o uguali a zero?) then (<color:#f2f230> sì)
#0fff50 :prendi il controllo del nodo;
else (<color:#f2f230> no)
  :Sottrai i punti danno
  dai PF __effettivi__ del nodo.;
note right
Attivazione
software nodo
endnote
endif
if (numero di punti danno rimanenti
    maggiori di zero?) then (<color:#f2f230> sì)
:sottrai il totale rimanente di
punti danno dall'INF del nodo;
note right
Attivazione
software nodo
endnote
:Esegui una prova di danno critico;
if (Prova superata?) then (<color:#f2f230> sì)
  end
else (<color:#f2f230> no)
  :applica gli effetti 
  dei danni critici;
  note right
  Attivazione
  software nodo
  endnote
endif
else (<color:#f2f230> no)
 end
endif
end
@enduml

@startuml "Attacco ICE"
title "Attacco ICE"
skinparam defaultFontName Oxanium
skinparam activity {
  StartColor #0fff50
  BarColor #2c84fa
  EndColor #e949f5
  BorderColor #2c84fa
  ArrowColor #2c84fa
  FontName Oxanium
}
start
:Tira il dado ICE;
note right
Attivazione software
dell'hacker
endnote 
:Sottrai l'armatura di INF dell'haker
al risultato del tiro;

if (PF dell'hacker inferiori o uguali a zero?) then (<color:#f2f230> sì)
#e949f5 :L'hacker non può muoversi \nnella rete o disconnettersi;
else (<color:#f2f230> no)
 :Sottrai i punti danno
 dai PF __effettivi__ dell'hacker;
 note right
Attivazione software
dell'hacker
 endnote
endif
if (punti danno maggiori al livello PF dell'hacker?) then (<color:#f2f230> sì)
:sottrai la quantità rimanente di punti danno
dall'INF dell'hacker;
note right
  Attivazione software
  dell'hacker
endnote
:Esegui una prova di danno critico;
if (Prova superata?) then (<color:#f2f230> sì)
  end
else (<color:#f2f230> no)
  :applica gli effetti \n del danno critico;
  note right
  Attivazione software
  dell'hacker
  endnote
  if (Black ICE) then (<color:#f2f230> sì)
  :sottrarre dalla PSI dell'hacker 
  gli stessi punti sottratti alla INF;
  endif
endif
else (<color:#f2f230> no)
 end
endif
end
@enduml