export const messages_en = {
  activated: "attivato",
  ACTIV: "ACT",
  activation_desc:
    "Livello di attivazione software aggiuntivo. \nSe il tiro di danno è uguale o inferiore al valore,\n viene attivato più software di difesa.",
  Add: "Aggiungi",
  Armor: "Armatura",
  Background: "Background",
  BIO: "BIO",
  bytes: "bytes",
  BLACK_ICE: "Black ICE",
  Browser_ID: "ID Browser",
  Character: "Personaggio",
  Characters: "Personaggi",
  Class: "Classe",
  Clean: "Pulisci",
  Clear: "Cancella",
  Client: "Client",
  Close: "Chiudi",
  Color: "Colore",
  Comment: "Commento",
  Configuration: "Configurazione",
  config_current_storage: "Lo spazio di archiviazione corrente è",
  config_storage_info: `Ricorda che questa app utilizza l'archiviazione del browser locale
  al posto di un database. Il limite più diffuso per tale archiviazione è di circa 5 MB.`,
  config_network_desc1: `Se hai accesso ad alcuni server MQTT con Websocket, puoi fargli
  condividere i tiri dei dadi e le note del tabellone con altri utenti. Seleziona
  Modalità "Host" o "Client" di seguito.`,
  config_network_desc2: `In modalità "Host", sono necessari solo l'indirizzo e le credenziali del server MQTT
  (se necessario), per 'Client' dovrebbe essere fornito anche un ID del
  browser di hosting.`,
  Connection_link: "Link di connessione",
  Content: "Contenuto",
  Corporation: "Corporazione",
  Credits: "Crediti",
  Credentials: "Credenziali",
  Cyberdeck: "Cyberdeck",
  Cybermods: "Cybermodifiche",
  d10: "d10",
  d100: "d100",
  d12: "d12",
  d20: "d20",
  d4: "d4",
  d6: "d6",
  d8: "d8",
  Data: "Data",
  Delete_character: "Cancella personaggio",
  Delete_item: "Cancella oggetto",
  Delete_selected: "Cancella selezione",
  Deprived: "Esausto",
  Detail: "Dettaglio",
  dice_letter: "d",
  dmg_dice: "dado di danno",
  Draw: "Pesca",
  Edit: "Modifica",
  Employee_profile: "Profilo impiegato",
  Export: "Esporta",
  Generate: "Genera",
  Generator: "Generatore",
  Gossip: "Gossip",
  Host: "Host",
  HP: "PF",
  HTML_code: "Codice HTML",
  Identification: "Identificazione",
  Import: "Importa",
  INF: "INF",
  ICE: "ICE",
  Infosphere: "Infosfera",
  Infosphere_node: "Nodo dell'Infosfera",
  Input_comment: "Inserisci commento per il tiro",
  inventory_fatigued: "affaticato",
  inventory_total: "totale",
  Inventory: "Inventario",
  Items: "Oggetti",
  Messages: "Messagggi",
  Name: "Nome",
  Network_connection: "Connessione di rete",
  No: "No",
  Note: "Nota",
  Notes: "Note",
  NPC: "PNG",
  Objective: "Obiettivo",
  Programs: "Programmi",
  PSY: "PSI",
  Really_delete_character: "Elimina davvero il personaggio",
  Really_delete_message: "Elimina davvero il messaggio",
  Really_delete_track: "Elimina davvero la traccia",
  Remote_Browser_ID: "ID del browser remoto",
  Resources: "Risorse",
  Roll: "Tiro",
  Save: "Salva",
  Sector: "Settore",
  Select: "Seleziona",
  Select_generator: "Seleziona il generatore",
  Server_address: "Indirizzo del server",
  Shape: "Forma",
  Share: "Condividi",
  Shared: "Condiviso",
  Storage: "Storage",
  Subscription: "Sottoscrizione",
  Title: "Titolo",
  total: "totale",
  Tracker: "Localizzatore",
  Username: "Username",
  Yes: "Si",
};
